### ISSUE TITLE
PHP User Deprecation Warnings

### ISSUE THREAD

**Issue by boskabouter007** [compucorp/uk.co.compucorp.civicrm.pivotreport#141]
Pivot Report: Version 2.0.7

Upgraded env. from: Drupal 10.2.3 - CiviCRM 5.70.2 - PHP version 8.2.18
to:  Drupal 10.2.6 - CiviCRM 5.73.1 - PHP version 8.2.18

[PHP User Deprecation] Permission 'access CiviCRM pivot table reports' should be declared with 'label' and 'description' keys. 
See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/
Caller: CRM_Core_Permission::assembleBasicPermissions at /var/www/vhosts/<*domain*>.be/httpdocs/vendor/civicrm/civicrm-core/CRM/Core/Error.php:1132
[PHP User Deprecation] Permission 'Admin Pivot Report' should be declared with 'label' and 'description' keys. 
See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/ 
Caller: CRM_Core_Permission::assembleBasicPermissions at /var/www/vhosts/<*domain*>/httpdocs/vendor/civicrm/civicrm-core/CRM/Core/Error.php:1132

**Comment by MegaphoneJon** [comment]
@boskabouter007 Here's a fix: https://github.com/compucorp/uk.co.compucorp.civicrm.pivotreport/pull/142
